version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper:2888:3888
    restart: always

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "crypto_data:1:1:compact"
    restart: always
  
  cryptopulse:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crypto-pulse
    restart: always
    depends_on:
      - kafka
    environment:
      KAFKA_BROKERS: kafka:9092
      KAFKA_CRYPTO_TOPIC: crypto_data
      BINANCE_SPOT_WS_URL: wss://stream.binance.com:443/ws/!ticker@arr
      BINANCE_USD_M_FUT_WS_URL: wss://fstream.binance.com/ws/!ticker@arr
      BINANCE_COIN_M_FUT_WS_URL: wss://dstream.binance.com/ws/!ticker@arr
      WEBSOCKET_FAIL_THRESHOLD: 10
      MESSAGE_FAIL_THRESHOLD: 10
      KAFKA_CONNECTION_FAIL_THRESHOLD: 10
